services:
  - type: web
    name: mero-allotment
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: IPO_WEB_SECRET
        generateValue: true
